[package]
name = "did-offchain-trade-rpc"
version = "2.0.0-alpha.5"
authors = ["Tatsuki Hashimoto"]
edition = "2018"

[dependencies]
codec = { package = "parity-scale-codec", version = "1.0.0" }
jsonrpc-core = "14.0.3"
jsonrpc-core-client = "14.0.3"
jsonrpc-derive = "14.0.3"
serde = { version = "1.0.101", features = ["derive"], optional = true }

sp-rpc = { version = '2.0.0-alpha.5', default_features = false}
sp-runtime = { version = '2.0.0-alpha.5', default_features = false}
sp-blockchain = { version = '2.0.0-alpha.5', default_features = false}
sp-api = { version = '2.0.0-alpha.5', default_features = false }

did-offchain-trade-rpc-runtime-api = { version = "2.0.0-alpha.5", path = "./runtime-api", default_features = false }

[features]
default = ["std"]
std = [
    "serde",
    "sp-runtime/std",
    "sp-api/std",
    "did-offchain-trade-rpc-runtime-api/std"
]